### ISSUE TITLE
Convert module to pip installable module

### ISSUE THREAD

**Issue by creyD** [creyD/entro.py#2]
This could be a small efficient and easy to use pip module and it just has to be converted! As I tried it already but didn't get it to work, I would like to invite anyone with more experience to try it.

**Comment by ptrstr** [comment]
I'd like to take on this. Could you assign me to it?

**Comment by ptrstr** [comment]
PR #4 fixes this

**Comment by creyD** [comment]
Thank you! @ptrstr :)
